version: '3.6'

networks:
  docker_test:
    external: true

services:
  ordermanagement.org1.example.com:
    build: .
    container_name: ordermanagement.org1.example.com
    hostname: ordermanagement.org1.example.com
    volumes:
      - ./crypto:/crypto
    env_file:
      - chaincode1.env
    networks:
      docker_test:
    expose:
      - 9999

  ordermanagement.org2.example.com:
    build: .
    container_name: ordermanagement.org2.example.com
    hostname: ordermanagement.org2.example.com
    volumes:
      - ./crypto:/crypto
    env_file:
      - chaincode2.env
    networks:
      docker_test:
    expose:
      - 9999
